// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ApplicationSource = {
    /**
     * Public git repository.
     */
    PublicGit: "public-git",
    /**
     * Private git repository accessed with a Coolify private key.
     */
    PrivateDeployKey: "private-deploy-key",
    /**
     * Private GitHub repository accessed through a GitHub App.
     */
    PrivateGitHubApp: "private-github-app",
    /**
     * Prebuilt image from a Docker registry.
     */
    DockerImage: "docker-image",
    /**
     * Inline Dockerfile.
     */
    Dockerfile: "dockerfile",
} as const;

export type ApplicationSource = (typeof ApplicationSource)[keyof typeof ApplicationSource];

export const DatabaseType = {
    /**
     * PostgreSQL
     */
    PostgreSQL: "postgresql",
    /**
     * MySQL
     */
    MySQL: "mysql",
    /**
     * MariaDB
     */
    MariaDB: "mariadb",
    /**
     * MongoDB
     */
    MongoDB: "mongodb",
    /**
     * Redis
     */
    Redis: "redis",
    /**
     * KeyDB
     */
    KeyDB: "keydb",
    /**
     * Dragonfly
     */
    Dragonfly: "dragonfly",
    /**
     * ClickHouse
     */
    ClickHouse: "clickhouse",
} as const;

export type DatabaseType = (typeof DatabaseType)[keyof typeof DatabaseType];

export const StorageType = {
    /**
     * Named Docker volume.
     */
    Persistent: "persistent",
    /**
     * Host directory mounted into the container.
     */
    Directory: "directory",
} as const;

export type StorageType = (typeof StorageType)[keyof typeof StorageType];
