// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("coolify");

/**
 * Coolify read/write API token (Coolify > Security > API tokens). Defaults to the COOLIFY_API_TOKEN environment variable.
 */
export declare const apiToken: string;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken") ?? (utilities.getEnv("COOLIFY_API_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * Base URL of the Coolify instance without the API path, e.g. https://coolify.example.com. Defaults to the COOLIFY_BASE_URL environment variable.
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("COOLIFY_BASE_URL") || "");
    },
    enumerable: true,
});

/**
 * Tags attached to every application, database and service in addition to their own tags. Defaults to ["pulumi"]; use disableDefaultTags to attach none.
 */
export declare const defaultTags: string[] | undefined;
Object.defineProperty(exports, "defaultTags", {
    get() {
        return __config.getObject<string[]>("defaultTags");
    },
    enumerable: true,
});

/**
 * Attach no default tags at all. Needed because an empty defaultTags list is indistinguishable from an unset one.
 */
export declare const disableDefaultTags: boolean | undefined;
Object.defineProperty(exports, "disableDefaultTags", {
    get() {
        return __config.getObject<boolean>("disableDefaultTags");
    },
    enumerable: true,
});

