package provider

import (
	"context"
	"fmt"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// Database manages a standalone database (PostgreSQL, Redis, ...) inside a
// Coolify project environment.
type Database struct{}

type DatabaseArgs struct {
	// Database type: "redis" or "postgresql".
	Type string `pulumi:"type"`
	// Name of the database.
	Name string `pulumi:"name"`
	// Description of the database.
	Description string `pulumi:"description,optional"`
	// Container image, e.g. "postgres:18-alpine".
	Image string `pulumi:"image,optional"`
	// Whether the database is exposed publicly.
	IsPublic bool `pulumi:"isPublic,optional"`
	// Public port to expose. Required when isPublic is true.
	PublicPort *int `pulumi:"publicPort,optional"`
	// Name of the Coolify project the database belongs to.
	Project string `pulumi:"project"`
	// Name of the environment inside the project.
	Environment string `pulumi:"environment"`
	// UUID of the server hosting the database.
	ServerUUID string `pulumi:"serverUuid"`
}

type DatabaseState struct {
	// UUID of the database in Coolify.
	UUID string `pulumi:"uuid"`
	// Database type: "redis" or "postgresql".
	Type string `pulumi:"type"`
	// Name of the database.
	Name string `pulumi:"name"`
	// Description of the database.
	Description string `pulumi:"description"`
	// Container image.
	Image string `pulumi:"image"`
	// Whether the database is exposed publicly.
	IsPublic bool `pulumi:"isPublic"`
	// Public port, if exposed.
	PublicPort *int `pulumi:"publicPort,optional"`
	// Name of the Coolify project.
	Project string `pulumi:"project"`
	// Name of the environment.
	Environment string `pulumi:"environment"`
	// UUID of the server hosting the database.
	ServerUUID string `pulumi:"serverUuid"`
	// ID of the Coolify environment the database lives in.
	EnvironmentID int `pulumi:"environmentId"`
	// UUID of the owning project.
	ProjectUUID string `pulumi:"projectUuid"`
	// Internal connection URL (never compared or patched).
	InternalURL *string `pulumi:"internalUrl,optional"`
	// External connection URL (never compared or patched).
	ExternalURL *string `pulumi:"externalUrl,optional"`
	// PostgreSQL user (never compared or patched).
	PostgresUser *string `pulumi:"postgresUser,optional"`
	// PostgreSQL database name (never compared or patched).
	PostgresDatabase *string `pulumi:"postgresDatabase,optional"`
	// Database password (never compared or patched).
	Password *string `pulumi:"password,optional" provider:"secret"`
}

func (r *Database) Annotate(a infer.Annotator) {
	a.SetToken("index", "Database")
	a.Describe(&r, "A standalone Coolify database (Redis, PostgreSQL) inside a project environment.")
}

func (args *DatabaseArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.Type, `Database type: "redis" or "postgresql".`)
	a.Describe(&args.PublicPort, "Public port to expose. Required when isPublic is true.")
}

func (state *DatabaseState) Annotate(a infer.Annotator) {
	a.Describe(&state.Password, "Database password generated by Coolify. Never compared or patched.")
}

func (Database) Create(ctx context.Context, req infer.CreateRequest[DatabaseArgs]) (infer.CreateResponse[DatabaseState], error) {
	if err := validatePublicPort(req.Inputs); err != nil {
		return infer.CreateResponse[DatabaseState]{}, err
	}
	if req.DryRun {
		return infer.CreateResponse[DatabaseState]{ID: "pending", Output: databasePlaceholder(req.Inputs)}, nil
	}
	c := client(ctx)
	state, err := syncDatabase(ctx, c, req.Inputs)
	if err != nil {
		return infer.CreateResponse[DatabaseState]{}, err
	}
	return infer.CreateResponse[DatabaseState]{ID: state.UUID, Output: state}, nil
}

func (Database) Diff(ctx context.Context, req infer.DiffRequest[DatabaseArgs, DatabaseState]) (infer.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}
	if req.Inputs.Type != req.State.Type {
		diff["type"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.Project != req.State.Project {
		diff["project"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.Environment != req.State.Environment {
		diff["environment"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.ServerUUID != req.State.ServerUUID {
		diff["serverUuid"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.Name != req.State.Name {
		diff["name"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.Description != req.State.Description {
		diff["description"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.Image != req.State.Image {
		diff["image"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.IsPublic != req.State.IsPublic {
		diff["isPublic"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.PublicPort != nil && !intPtrEqual(req.State.PublicPort, req.Inputs.PublicPort) {
		diff["publicPort"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.PublicPort == nil && req.State.PublicPort != nil {
		diff["publicPort"] = p.PropertyDiff{Kind: p.Update}
	}
	return infer.DiffResponse{HasChanges: len(diff) > 0, DetailedDiff: diff}, nil
}

func (Database) Update(ctx context.Context, req infer.UpdateRequest[DatabaseArgs, DatabaseState]) (infer.UpdateResponse[DatabaseState], error) {
	if err := validatePublicPort(req.Inputs); err != nil {
		return infer.UpdateResponse[DatabaseState]{}, err
	}
	if req.DryRun {
		return infer.UpdateResponse[DatabaseState]{
			Output: databaseStateWithUUID(req.State.UUID, req.State, req.Inputs),
		}, nil
	}
	c := client(ctx)
	state, err := syncDatabase(ctx, c, req.Inputs)
	if err != nil {
		return infer.UpdateResponse[DatabaseState]{}, err
	}
	return infer.UpdateResponse[DatabaseState]{Output: state}, nil
}

func (Database) Read(ctx context.Context, req infer.ReadRequest[DatabaseArgs, DatabaseState]) (infer.ReadResponse[DatabaseArgs, DatabaseState], error) {
	c := client(ctx)
	database, err := c.GetDatabase(ctx, req.ID)
	if err != nil {
		return infer.ReadResponse[DatabaseArgs, DatabaseState]{}, err
	}
	state, err := normalizeDatabaseState(ctx, database, req.State)
	if err != nil {
		return infer.ReadResponse[DatabaseArgs, DatabaseState]{}, err
	}
	inputs := req.Inputs
	if inputs.Name == "" {
		inputs = databaseInputsFromState(state)
	}
	return infer.ReadResponse[DatabaseArgs, DatabaseState]{ID: req.ID, Inputs: inputs, State: state}, nil
}

func (Database) Delete(ctx context.Context, req infer.DeleteRequest[DatabaseState]) (infer.DeleteResponse, error) {
	c := client(ctx)
	if err := c.DeleteDatabase(ctx, req.State.UUID); err != nil && !NotFound(err) {
		return infer.DeleteResponse{}, err
	}
	return infer.DeleteResponse{}, nil
}

func syncDatabase(ctx context.Context, c *Client, inputs DatabaseArgs) (DatabaseState, error) {
	identity, err := resolveDatabaseIdentity(ctx, c, inputs)
	if err != nil {
		return DatabaseState{}, err
	}

	databases, err := c.ListDatabases(ctx)
	if err != nil {
		return DatabaseState{}, err
	}
	var existing *CoolifyDatabase
	for i := range databases {
		candidate := &databases[i]
		if candidate.Name == inputs.Name && candidate.EnvironmentID == identity.environmentID {
			existing = candidate
			break
		}
	}

	if existing == nil {
		uuid, err := c.CreateDatabase(ctx, inputs.Type, CreateDatabaseInput{
			ServerUUID:      inputs.ServerUUID,
			ProjectUUID:     identity.projectUUID,
			EnvironmentName: identity.environment,
			Name:            inputs.Name,
			Description:     inputs.Description,
			Image:           inputs.Image,
			IsPublic:        inputs.IsPublic,
			PublicPort:      inputs.PublicPort,
		})
		if err != nil {
			return DatabaseState{}, err
		}
		database, err := c.GetDatabase(ctx, uuid)
		if err != nil {
			return DatabaseState{}, err
		}
		return databaseState(database, identity, inputs), nil
	}

	if err := assertCompatibleType(existing, inputs.Type); err != nil {
		return DatabaseState{}, err
	}
	changes := databaseChanges(existing, inputs)
	if len(changes) > 0 {
		if err := c.UpdateDatabase(ctx, existing.UUID, changes); err != nil {
			return DatabaseState{}, err
		}
		updated, err := c.GetDatabase(ctx, existing.UUID)
		if err != nil {
			return DatabaseState{}, err
		}
		return databaseState(updated, identity, inputs), nil
	}

	return databaseState(*existing, identity, inputs), nil
}

type databaseIdentity struct {
	environmentID int
	projectUUID   string
	environment   string
}

func resolveDatabaseIdentity(ctx context.Context, c *Client, inputs DatabaseArgs) (databaseIdentity, error) {
	projects, err := c.ListProjects(ctx)
	if err != nil {
		return databaseIdentity{}, err
	}
	var project *CoolifyProject
	for i := range projects {
		if projects[i].Name == inputs.Project {
			project = &projects[i]
			break
		}
	}
	if project == nil {
		return databaseIdentity{}, fmt.Errorf(`coolify project %q not found for database %q`, inputs.Project, inputs.Name)
	}

	environments, err := c.ListEnvironments(ctx, project.UUID)
	if err != nil {
		return databaseIdentity{}, err
	}
	for i := range environments {
		if environments[i].Name == inputs.Environment {
			return databaseIdentity{
				environmentID: environments[i].ID,
				projectUUID:   project.UUID,
				environment:   environments[i].Name,
			}, nil
		}
	}
	return databaseIdentity{}, fmt.Errorf(`coolify environment %q not found in project %q for database %q`, inputs.Environment, inputs.Project, inputs.Name)
}

func assertCompatibleType(database *CoolifyDatabase, typ string) error {
	expected := "standalone-redis"
	if typ == "postgresql" {
		expected = "standalone-postgresql"
	}
	if database.DatabaseType != expected {
		return fmt.Errorf(`coolify database %q has type %q, expected %q`, database.Name, database.DatabaseType, expected)
	}
	return nil
}

func databaseChanges(database *CoolifyDatabase, inputs DatabaseArgs) map[string]any {
	changes := map[string]any{}
	if database.Name != inputs.Name {
		changes["name"] = inputs.Name
	}
	if desc(database.Description) != inputs.Description {
		changes["description"] = inputs.Description
	}
	if database.Image != inputs.Image {
		changes["image"] = inputs.Image
	}
	if database.IsPublic != inputs.IsPublic {
		changes["is_public"] = inputs.IsPublic
	}
	if inputs.PublicPort != nil && !intPtrEqual(database.PublicPort, inputs.PublicPort) {
		changes["public_port"] = *inputs.PublicPort
	} else if inputs.PublicPort == nil && database.PublicPort != nil {
		changes["public_port"] = nil
	}
	return changes
}

func validatePublicPort(inputs DatabaseArgs) error {
	if inputs.IsPublic && inputs.PublicPort == nil {
		return fmt.Errorf(`coolify database %q must declare a publicPort when isPublic is true`, inputs.Name)
	}
	return nil
}

func normalizeDatabaseState(ctx context.Context, database CoolifyDatabase, prev DatabaseState) (DatabaseState, error) {
	return DatabaseState{
		UUID:             database.UUID,
		Type:             prev.Type,
		Name:             database.Name,
		Description:      desc(database.Description),
		Image:            database.Image,
		IsPublic:         database.IsPublic,
		PublicPort:       database.PublicPort,
		Project:          prev.Project,
		Environment:      prev.Environment,
		ServerUUID:       prev.ServerUUID,
		EnvironmentID:    database.EnvironmentID,
		ProjectUUID:      prev.ProjectUUID,
		InternalURL:      database.InternalDBURL,
		ExternalURL:      database.ExternalDBURL,
		PostgresUser:     database.PostgresUser,
		PostgresDatabase: database.PostgresDB,
		Password:         database.PostgresPass,
	}, nil
}

func databaseState(database CoolifyDatabase, identity databaseIdentity, inputs DatabaseArgs) DatabaseState {
	return DatabaseState{
		UUID:             database.UUID,
		Type:             inputs.Type,
		Name:             database.Name,
		Description:      desc(database.Description),
		Image:            database.Image,
		IsPublic:         database.IsPublic,
		PublicPort:       database.PublicPort,
		Project:          inputs.Project,
		Environment:      identity.environment,
		ServerUUID:       inputs.ServerUUID,
		EnvironmentID:    identity.environmentID,
		ProjectUUID:      identity.projectUUID,
		InternalURL:      database.InternalDBURL,
		ExternalURL:      database.ExternalDBURL,
		PostgresUser:     database.PostgresUser,
		PostgresDatabase: database.PostgresDB,
		Password:         database.PostgresPass,
	}
}

func databasePlaceholder(inputs DatabaseArgs) DatabaseState {
	return DatabaseState{
		UUID:          "pending",
		Type:          inputs.Type,
		Name:          inputs.Name,
		Description:   inputs.Description,
		Image:         inputs.Image,
		IsPublic:      inputs.IsPublic,
		PublicPort:    inputs.PublicPort,
		Project:       inputs.Project,
		Environment:   inputs.Environment,
		ServerUUID:    inputs.ServerUUID,
		EnvironmentID: -1,
		ProjectUUID:   "pending",
	}
}

func databaseStateWithUUID(uuid string, prev DatabaseState, inputs DatabaseArgs) DatabaseState {
	state := databasePlaceholder(inputs)
	state.UUID = uuid
	state.EnvironmentID = prev.EnvironmentID
	state.ProjectUUID = prev.ProjectUUID
	state.InternalURL = prev.InternalURL
	state.ExternalURL = prev.ExternalURL
	state.PostgresUser = prev.PostgresUser
	state.PostgresDatabase = prev.PostgresDatabase
	state.Password = prev.Password
	return state
}

func databaseInputsFromState(state DatabaseState) DatabaseArgs {
	return DatabaseArgs{
		Type:        state.Type,
		Name:        state.Name,
		Description: state.Description,
		Image:       state.Image,
		IsPublic:    state.IsPublic,
		PublicPort:  state.PublicPort,
		Project:     state.Project,
		Environment: state.Environment,
		ServerUUID:  state.ServerUUID,
	}
}

func intPtrEqual(a, b *int) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}
