// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Coolify application built from a git repository, a Docker image, or a Dockerfile.
 */
export class Application extends pulumi.CustomResource {
    /**
     * Get an existing Application resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Application {
        return new Application(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Application';

    /**
     * Returns true if the given object is an instance of Application.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Application {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Application.__pulumiType;
    }

    declare public readonly autoDeployEnabled: pulumi.Output<boolean>;
    declare public readonly buildPack: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly environment: pulumi.Output<string>;
    declare public readonly environmentVariables: pulumi.Output<{[key: string]: string}>;
    /**
     * The FQDN Coolify exposes the application at.
     */
    declare public /*out*/ readonly fqdn: pulumi.Output<string>;
    declare public readonly gitBranch: pulumi.Output<string>;
    declare public readonly gitRepository: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly project: pulumi.Output<string>;
    declare public readonly serverUuid: pulumi.Output<string>;
    declare public readonly source: pulumi.Output<string>;
    /**
     * Status reported by Coolify.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Application resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.serverUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverUuid'");
            }
            resourceInputs["autoDeployEnabled"] = args?.autoDeployEnabled;
            resourceInputs["baseDirectory"] = args?.baseDirectory;
            resourceInputs["buildCommand"] = args?.buildCommand;
            resourceInputs["buildPack"] = args?.buildPack;
            resourceInputs["description"] = args?.description;
            resourceInputs["dockerRegistryImageName"] = args?.dockerRegistryImageName;
            resourceInputs["dockerRegistryImageTag"] = args?.dockerRegistryImageTag;
            resourceInputs["dockerfile"] = args?.dockerfile;
            resourceInputs["dockerfileLocation"] = args?.dockerfileLocation;
            resourceInputs["domains"] = args?.domains;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["environmentVariables"] = args?.environmentVariables;
            resourceInputs["forceHttpsEnabled"] = args?.forceHttpsEnabled;
            resourceInputs["gitBranch"] = args?.gitBranch;
            resourceInputs["gitCommitSha"] = args?.gitCommitSha;
            resourceInputs["gitRepository"] = args?.gitRepository;
            resourceInputs["githubAppUuid"] = args?.githubAppUuid;
            resourceInputs["healthCheckEnabled"] = args?.healthCheckEnabled;
            resourceInputs["healthCheckMethod"] = args?.healthCheckMethod;
            resourceInputs["healthCheckPath"] = args?.healthCheckPath;
            resourceInputs["healthCheckPort"] = args?.healthCheckPort;
            resourceInputs["installCommand"] = args?.installCommand;
            resourceInputs["instantDeploy"] = args?.instantDeploy;
            resourceInputs["limitsCPUs"] = args?.limitsCPUs;
            resourceInputs["limitsMemory"] = args?.limitsMemory;
            resourceInputs["name"] = args?.name;
            resourceInputs["portsExposes"] = args?.portsExposes;
            resourceInputs["portsMappings"] = args?.portsMappings;
            resourceInputs["previewDeploymentsEnabled"] = args?.previewDeploymentsEnabled;
            resourceInputs["privateKeyUuid"] = args?.privateKeyUuid;
            resourceInputs["project"] = args?.project;
            resourceInputs["publishDirectory"] = args?.publishDirectory;
            resourceInputs["serverUuid"] = args?.serverUuid;
            resourceInputs["source"] = args?.source;
            resourceInputs["startCommand"] = args?.startCommand;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["fqdn"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["autoDeployEnabled"] = undefined /*out*/;
            resourceInputs["buildPack"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["environment"] = undefined /*out*/;
            resourceInputs["environmentVariables"] = undefined /*out*/;
            resourceInputs["fqdn"] = undefined /*out*/;
            resourceInputs["gitBranch"] = undefined /*out*/;
            resourceInputs["gitRepository"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["serverUuid"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Application.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Application resource.
 */
export interface ApplicationArgs {
    autoDeployEnabled?: pulumi.Input<boolean | undefined>;
    baseDirectory?: pulumi.Input<string | undefined>;
    buildCommand?: pulumi.Input<string | undefined>;
    buildPack?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    dockerRegistryImageName?: pulumi.Input<string | undefined>;
    dockerRegistryImageTag?: pulumi.Input<string | undefined>;
    dockerfile?: pulumi.Input<string | undefined>;
    dockerfileLocation?: pulumi.Input<string | undefined>;
    domains?: pulumi.Input<string | undefined>;
    environment: pulumi.Input<string>;
    /**
     * Environment variables applied to the application. Declared keys missing on the Coolify side are created as hidden values; existing keys are never patched and undeclared keys are left untouched.
     */
    environmentVariables?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    forceHttpsEnabled?: pulumi.Input<boolean | undefined>;
    gitBranch?: pulumi.Input<string | undefined>;
    gitCommitSha?: pulumi.Input<string | undefined>;
    gitRepository?: pulumi.Input<string | undefined>;
    githubAppUuid?: pulumi.Input<string | undefined>;
    healthCheckEnabled?: pulumi.Input<boolean | undefined>;
    healthCheckMethod?: pulumi.Input<string | undefined>;
    healthCheckPath?: pulumi.Input<string | undefined>;
    healthCheckPort?: pulumi.Input<string | undefined>;
    installCommand?: pulumi.Input<string | undefined>;
    instantDeploy?: pulumi.Input<boolean | undefined>;
    limitsCPUs?: pulumi.Input<string | undefined>;
    limitsMemory?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    portsExposes?: pulumi.Input<string | undefined>;
    portsMappings?: pulumi.Input<string | undefined>;
    previewDeploymentsEnabled?: pulumi.Input<boolean | undefined>;
    privateKeyUuid?: pulumi.Input<string | undefined>;
    project: pulumi.Input<string>;
    publishDirectory?: pulumi.Input<string | undefined>;
    serverUuid: pulumi.Input<string>;
    source?: pulumi.Input<string | undefined>;
    startCommand?: pulumi.Input<string | undefined>;
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
