// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A standalone Coolify database (PostgreSQL, MySQL, MariaDB, MongoDB, Redis, KeyDB, Dragonfly, ClickHouse) inside a project environment. An existing database with the same name in the environment is adopted on create.
 */
export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    /**
     * Tags the provider attached: the provider's default tags plus the declared ones.
     */
    declare public /*out*/ readonly appliedTags: pulumi.Output<string[] | undefined>;
    /**
     * Name of the default database, for engines that have one.
     */
    declare public /*out*/ readonly databaseName: pulumi.Output<string>;
    /**
     * Description of the database.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * ID of the Coolify environment the database lives in.
     */
    declare public /*out*/ readonly environmentId: pulumi.Output<number>;
    /**
     * Name of the environment inside the project. Changing it moves the resource in place; the environment must already exist.
     */
    declare public readonly environmentName: pulumi.Output<string>;
    /**
     * Public connection URL, when exposed.
     */
    declare public /*out*/ readonly externalUrl: pulumi.Output<string>;
    /**
     * Container image, e.g. "postgres:17-alpine". Leave unset to keep Coolify's default.
     */
    declare public readonly image: pulumi.Output<string | undefined>;
    /**
     * Start the database right after creating it.
     */
    declare public readonly instantDeploy: pulumi.Output<boolean | undefined>;
    /**
     * Connection URL for resources on the same Docker network.
     */
    declare public /*out*/ readonly internalUrl: pulumi.Output<string>;
    /**
     * Whether the database is exposed publicly.
     */
    declare public readonly isPublic: pulumi.Output<boolean | undefined>;
    /**
     * Name of the database. An existing database with this name in the same environment is adopted.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Password of the primary database user.
     */
    declare public /*out*/ readonly password: pulumi.Output<string>;
    /**
     * UUID of the Coolify project (the uuid output of a Project resource). Changing it moves the resource to the new project in place.
     */
    declare public readonly projectUuid: pulumi.Output<string>;
    /**
     * Public port to expose. Required when isPublic is true.
     */
    declare public readonly publicPort: pulumi.Output<number | undefined>;
    /**
     * UUID of the server hosting the database (the uuid output of a Server resource).
     */
    declare public readonly serverUuid: pulumi.Output<string>;
    /**
     * Status reported by Coolify.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Tags attached to the database in addition to the provider's default tags. Declared tags are attached, tags removed from the declaration are detached, tags added in the Coolify UI are left untouched.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Database engine.
     */
    declare public readonly type: pulumi.Output<enums.DatabaseType>;
    /**
     * Username of the primary database user.
     */
    declare public /*out*/ readonly username: pulumi.Output<string>;
    /**
     * UUID of the database in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentName === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentName'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.projectUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectUuid'");
            }
            if (args?.serverUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverUuid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["environmentName"] = args?.environmentName;
            resourceInputs["image"] = args?.image;
            resourceInputs["instantDeploy"] = args?.instantDeploy;
            resourceInputs["isPublic"] = args?.isPublic;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectUuid"] = args?.projectUuid;
            resourceInputs["publicPort"] = args?.publicPort;
            resourceInputs["serverUuid"] = args?.serverUuid;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["type"] = args?.type;
            resourceInputs["appliedTags"] = undefined /*out*/;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["externalUrl"] = undefined /*out*/;
            resourceInputs["internalUrl"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["appliedTags"] = undefined /*out*/;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["environmentName"] = undefined /*out*/;
            resourceInputs["externalUrl"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["instantDeploy"] = undefined /*out*/;
            resourceInputs["internalUrl"] = undefined /*out*/;
            resourceInputs["isPublic"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["projectUuid"] = undefined /*out*/;
            resourceInputs["publicPort"] = undefined /*out*/;
            resourceInputs["serverUuid"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["externalUrl", "internalUrl", "password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    /**
     * Description of the database.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the environment inside the project. Changing it moves the resource in place; the environment must already exist.
     */
    environmentName: pulumi.Input<string>;
    /**
     * Container image, e.g. "postgres:17-alpine". Leave unset to keep Coolify's default.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * Start the database right after creating it.
     */
    instantDeploy?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the database is exposed publicly.
     */
    isPublic?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the database. An existing database with this name in the same environment is adopted.
     */
    name: pulumi.Input<string>;
    /**
     * UUID of the Coolify project (the uuid output of a Project resource). Changing it moves the resource to the new project in place.
     */
    projectUuid: pulumi.Input<string>;
    /**
     * Public port to expose. Required when isPublic is true.
     */
    publicPort?: pulumi.Input<number | undefined>;
    /**
     * UUID of the server hosting the database (the uuid output of a Server resource).
     */
    serverUuid: pulumi.Input<string>;
    /**
     * Tags attached to the database in addition to the provider's default tags. Declared tags are attached, tags removed from the declaration are detached, tags added in the Coolify UI are left untouched.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Database engine.
     */
    type: pulumi.Input<enums.DatabaseType>;
}
