// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A standalone Coolify database (Redis, PostgreSQL) inside a project environment.
 */
export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    declare public readonly description: pulumi.Output<string>;
    declare public readonly environment: pulumi.Output<string>;
    declare public /*out*/ readonly environmentId: pulumi.Output<number>;
    declare public /*out*/ readonly externalUrl: pulumi.Output<string | undefined>;
    declare public readonly image: pulumi.Output<string>;
    declare public /*out*/ readonly internalUrl: pulumi.Output<string | undefined>;
    declare public readonly isPublic: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Database password generated by Coolify. Never compared or patched.
     */
    declare public /*out*/ readonly password: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly postgresDatabase: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly postgresUser: pulumi.Output<string | undefined>;
    declare public readonly project: pulumi.Output<string>;
    declare public /*out*/ readonly projectUuid: pulumi.Output<string>;
    declare public readonly publicPort: pulumi.Output<number | undefined>;
    declare public readonly serverUuid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.serverUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverUuid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["image"] = args?.image;
            resourceInputs["isPublic"] = args?.isPublic;
            resourceInputs["name"] = args?.name;
            resourceInputs["project"] = args?.project;
            resourceInputs["publicPort"] = args?.publicPort;
            resourceInputs["serverUuid"] = args?.serverUuid;
            resourceInputs["type"] = args?.type;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["externalUrl"] = undefined /*out*/;
            resourceInputs["internalUrl"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["postgresDatabase"] = undefined /*out*/;
            resourceInputs["postgresUser"] = undefined /*out*/;
            resourceInputs["projectUuid"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["environment"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["externalUrl"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["internalUrl"] = undefined /*out*/;
            resourceInputs["isPublic"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["postgresDatabase"] = undefined /*out*/;
            resourceInputs["postgresUser"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["projectUuid"] = undefined /*out*/;
            resourceInputs["publicPort"] = undefined /*out*/;
            resourceInputs["serverUuid"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    description?: pulumi.Input<string | undefined>;
    environment: pulumi.Input<string>;
    image?: pulumi.Input<string | undefined>;
    isPublic?: pulumi.Input<boolean | undefined>;
    name: pulumi.Input<string>;
    project: pulumi.Input<string>;
    /**
     * Public port to expose. Required when isPublic is true.
     */
    publicPort?: pulumi.Input<number | undefined>;
    serverUuid: pulumi.Input<string>;
    /**
     * Database type: "redis" or "postgresql".
     */
    type: pulumi.Input<string>;
}
