// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A scheduled backup configuration of a standalone Coolify database, optionally uploaded to an S3 storage. An existing configuration with the identical frequency on the database is adopted on create. Redis, KeyDB and Dragonfly do not support backups.
 */
export class DatabaseBackup extends pulumi.CustomResource {
    /**
     * Get an existing DatabaseBackup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DatabaseBackup {
        return new DatabaseBackup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:DatabaseBackup';

    /**
     * Returns true if the given object is an instance of DatabaseBackup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabaseBackup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabaseBackup.__pulumiType;
    }

    /**
     * Run a backup right after creating the configuration. Only relevant on create.
     */
    declare public readonly backupNow: pulumi.Output<boolean | undefined>;
    /**
     * UUID of the Coolify database to back up (the uuid output of a Database resource). Changing it replaces the configuration.
     */
    declare public readonly databaseUuid: pulumi.Output<string>;
    /**
     * Comma separated list of databases to dump. Leave unset to keep Coolify's default, the database's primary database.
     */
    declare public readonly databasesToBackup: pulumi.Output<string | undefined>;
    /**
     * Also delete the uploaded S3 files when the configuration is destroyed.
     */
    declare public readonly deleteS3Files: pulumi.Output<boolean | undefined>;
    /**
     * Dump all databases of the server instead of the listed ones.
     */
    declare public readonly dumpAll: pulumi.Output<boolean | undefined>;
    /**
     * Whether the schedule is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Cron expression or Coolify shorthand such as "daily" or "0 3 * * *". An existing configuration with the identical frequency string on the database is adopted on create; Coolify's own default schedule uses "0 0 * * *".
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Number of backups kept locally; 0 keeps all. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionAmountLocally: pulumi.Output<number | undefined>;
    /**
     * Number of backups kept in S3; 0 keeps all. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionAmountS3: pulumi.Output<number | undefined>;
    /**
     * Days local backups are kept; 0 keeps them forever. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionDaysLocally: pulumi.Output<number | undefined>;
    /**
     * Days S3 backups are kept; 0 keeps them forever. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionDaysS3: pulumi.Output<number | undefined>;
    /**
     * Maximum local storage in GB; 0 is unlimited. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionMaxStorageLocally: pulumi.Output<number | undefined>;
    /**
     * Maximum S3 storage in GB; 0 is unlimited. Leave unset to keep Coolify's default.
     */
    declare public readonly retentionMaxStorageS3: pulumi.Output<number | undefined>;
    /**
     * UUID of the S3 storage (the uuid output of an S3Storage resource). Required when saveS3 is true. Coolify does not report the configured storage, so drift on this input is not detected.
     */
    declare public readonly s3StorageUuid: pulumi.Output<string | undefined>;
    /**
     * Upload backups to an S3 storage.
     */
    declare public readonly saveS3: pulumi.Output<boolean | undefined>;
    /**
     * Timeout of a backup run in seconds, between 60 and 36000. Leave unset to keep Coolify's default.
     */
    declare public readonly timeout: pulumi.Output<number | undefined>;
    /**
     * UUID of the backup configuration in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a DatabaseBackup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseBackupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.databaseUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseUuid'");
            }
            if (args?.frequency === undefined && !opts.urn) {
                throw new Error("Missing required property 'frequency'");
            }
            resourceInputs["backupNow"] = args?.backupNow;
            resourceInputs["databaseUuid"] = args?.databaseUuid;
            resourceInputs["databasesToBackup"] = args?.databasesToBackup;
            resourceInputs["deleteS3Files"] = args?.deleteS3Files;
            resourceInputs["dumpAll"] = args?.dumpAll;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["retentionAmountLocally"] = args?.retentionAmountLocally;
            resourceInputs["retentionAmountS3"] = args?.retentionAmountS3;
            resourceInputs["retentionDaysLocally"] = args?.retentionDaysLocally;
            resourceInputs["retentionDaysS3"] = args?.retentionDaysS3;
            resourceInputs["retentionMaxStorageLocally"] = args?.retentionMaxStorageLocally;
            resourceInputs["retentionMaxStorageS3"] = args?.retentionMaxStorageS3;
            resourceInputs["s3StorageUuid"] = args?.s3StorageUuid;
            resourceInputs["saveS3"] = args?.saveS3;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["backupNow"] = undefined /*out*/;
            resourceInputs["databaseUuid"] = undefined /*out*/;
            resourceInputs["databasesToBackup"] = undefined /*out*/;
            resourceInputs["deleteS3Files"] = undefined /*out*/;
            resourceInputs["dumpAll"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["frequency"] = undefined /*out*/;
            resourceInputs["retentionAmountLocally"] = undefined /*out*/;
            resourceInputs["retentionAmountS3"] = undefined /*out*/;
            resourceInputs["retentionDaysLocally"] = undefined /*out*/;
            resourceInputs["retentionDaysS3"] = undefined /*out*/;
            resourceInputs["retentionMaxStorageLocally"] = undefined /*out*/;
            resourceInputs["retentionMaxStorageS3"] = undefined /*out*/;
            resourceInputs["s3StorageUuid"] = undefined /*out*/;
            resourceInputs["saveS3"] = undefined /*out*/;
            resourceInputs["timeout"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatabaseBackup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DatabaseBackup resource.
 */
export interface DatabaseBackupArgs {
    /**
     * Run a backup right after creating the configuration. Only relevant on create.
     */
    backupNow?: pulumi.Input<boolean | undefined>;
    /**
     * UUID of the Coolify database to back up (the uuid output of a Database resource). Changing it replaces the configuration.
     */
    databaseUuid: pulumi.Input<string>;
    /**
     * Comma separated list of databases to dump. Leave unset to keep Coolify's default, the database's primary database.
     */
    databasesToBackup?: pulumi.Input<string | undefined>;
    /**
     * Also delete the uploaded S3 files when the configuration is destroyed.
     */
    deleteS3Files?: pulumi.Input<boolean | undefined>;
    /**
     * Dump all databases of the server instead of the listed ones.
     */
    dumpAll?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the schedule is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Cron expression or Coolify shorthand such as "daily" or "0 3 * * *". An existing configuration with the identical frequency string on the database is adopted on create; Coolify's own default schedule uses "0 0 * * *".
     */
    frequency: pulumi.Input<string>;
    /**
     * Number of backups kept locally; 0 keeps all. Leave unset to keep Coolify's default.
     */
    retentionAmountLocally?: pulumi.Input<number | undefined>;
    /**
     * Number of backups kept in S3; 0 keeps all. Leave unset to keep Coolify's default.
     */
    retentionAmountS3?: pulumi.Input<number | undefined>;
    /**
     * Days local backups are kept; 0 keeps them forever. Leave unset to keep Coolify's default.
     */
    retentionDaysLocally?: pulumi.Input<number | undefined>;
    /**
     * Days S3 backups are kept; 0 keeps them forever. Leave unset to keep Coolify's default.
     */
    retentionDaysS3?: pulumi.Input<number | undefined>;
    /**
     * Maximum local storage in GB; 0 is unlimited. Leave unset to keep Coolify's default.
     */
    retentionMaxStorageLocally?: pulumi.Input<number | undefined>;
    /**
     * Maximum S3 storage in GB; 0 is unlimited. Leave unset to keep Coolify's default.
     */
    retentionMaxStorageS3?: pulumi.Input<number | undefined>;
    /**
     * UUID of the S3 storage (the uuid output of an S3Storage resource). Required when saveS3 is true. Coolify does not report the configured storage, so drift on this input is not detected.
     */
    s3StorageUuid?: pulumi.Input<string | undefined>;
    /**
     * Upload backups to an S3 storage.
     */
    saveS3?: pulumi.Input<boolean | undefined>;
    /**
     * Timeout of a backup run in seconds, between 60 and 36000. Leave unset to keep Coolify's default.
     */
    timeout?: pulumi.Input<number | undefined>;
}
