// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Looks up a storage (persistent volume or file/directory mount) of an application, database or service by mount path and/or volume name, e.g. to back it up with a VolumeBackup.
 */
export function getStorage(args?: GetStorageArgs, opts?: pulumi.InvokeOptions): Promise<GetStorageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coolify:index:getStorage", {
        "applicationUuid": args.applicationUuid,
        "databaseUuid": args.databaseUuid,
        "mountPath": args.mountPath,
        "name": args.name,
        "serviceUuid": args.serviceUuid,
    }, opts);
}

export interface GetStorageArgs {
    /**
     * UUID of the application owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    applicationUuid?: string;
    /**
     * UUID of the database owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    databaseUuid?: string;
    /**
     * Container mount path to look for. At least one of mountPath and name must be set.
     */
    mountPath?: string;
    /**
     * Volume name to look for, with or without Coolify's owner prefix. At least one of mountPath and name must be set.
     */
    name?: string;
    /**
     * UUID of the service owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    serviceUuid?: string;
}

export interface GetStorageResult {
    /**
     * Host directory of a directory mount.
     */
    readonly fsPath: string;
    /**
     * Host path of a persistent volume, when bound to one.
     */
    readonly hostPath: string;
    /**
     * Container mount path.
     */
    readonly mountPath: string;
    /**
     * Volume name as reported by Coolify.
     */
    readonly name: string;
    /**
     * UUID of the compose sub-resource the storage belongs to, for services.
     */
    readonly resourceUuid: string;
    /**
     * Storage type: persistent, directory or file.
     */
    readonly type: string;
    /**
     * UUID of the storage.
     */
    readonly uuid: string;
}
/**
 * Looks up a storage (persistent volume or file/directory mount) of an application, database or service by mount path and/or volume name, e.g. to back it up with a VolumeBackup.
 */
export function getStorageOutput(args?: GetStorageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetStorageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coolify:index:getStorage", {
        "applicationUuid": args.applicationUuid,
        "databaseUuid": args.databaseUuid,
        "mountPath": args.mountPath,
        "name": args.name,
        "serviceUuid": args.serviceUuid,
    }, opts);
}

export interface GetStorageOutputArgs {
    /**
     * UUID of the application owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    applicationUuid?: pulumi.Input<string | undefined>;
    /**
     * UUID of the database owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    databaseUuid?: pulumi.Input<string | undefined>;
    /**
     * Container mount path to look for. At least one of mountPath and name must be set.
     */
    mountPath?: pulumi.Input<string | undefined>;
    /**
     * Volume name to look for, with or without Coolify's owner prefix. At least one of mountPath and name must be set.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * UUID of the service owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set.
     */
    serviceUuid?: pulumi.Input<string | undefined>;
}
