// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A GitHub App source for deploying private repositories. An existing app with the same name is adopted on create. Create the app on GitHub first; Coolify only stores its credentials.
 */
export class GitHubApp extends pulumi.CustomResource {
    /**
     * Get an existing GitHubApp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): GitHubApp {
        return new GitHubApp(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:GitHubApp';

    /**
     * Returns true if the given object is an instance of GitHubApp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GitHubApp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GitHubApp.__pulumiType;
    }

    /**
     * GitHub API URL. Derived from htmlUrl when unset.
     */
    declare public readonly apiUrl: pulumi.Output<string | undefined>;
    /**
     * Numeric GitHub App ID.
     */
    declare public readonly appId: pulumi.Output<number>;
    /**
     * OAuth client ID of the app.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * OAuth client secret of the app.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * SSH port for git operations.
     */
    declare public readonly customPort: pulumi.Output<number>;
    /**
     * SSH user for git operations.
     */
    declare public readonly customUser: pulumi.Output<string>;
    /**
     * GitHub web URL.
     */
    declare public readonly htmlUrl: pulumi.Output<string>;
    /**
     * Installation ID of the app in the organization or account.
     */
    declare public readonly installationId: pulumi.Output<number>;
    /**
     * Numeric ID Coolify uses for the app in API paths.
     */
    declare public /*out*/ readonly internalId: pulumi.Output<number>;
    /**
     * Make the app available to all teams (self-hosted only).
     */
    declare public readonly isSystemWide: pulumi.Output<boolean | undefined>;
    /**
     * Name of the GitHub App in Coolify. An existing app with this name is adopted.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * GitHub organization the app is installed in. Leave unset for a personal account.
     */
    declare public readonly organization: pulumi.Output<string | undefined>;
    /**
     * UUID of the Coolify private key holding the app's private key (the uuid output of a PrivateKey resource).
     */
    declare public readonly privateKeyUuid: pulumi.Output<string>;
    /**
     * UUID of the GitHub App in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * Webhook secret of the app.
     */
    declare public readonly webhookSecret: pulumi.Output<string | undefined>;

    /**
     * Create a GitHubApp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GitHubAppArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.appId === undefined && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.installationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'installationId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.privateKeyUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'privateKeyUuid'");
            }
            resourceInputs["apiUrl"] = args?.apiUrl;
            resourceInputs["appId"] = args?.appId;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["customPort"] = (args?.customPort) ?? 22;
            resourceInputs["customUser"] = (args?.customUser) ?? "git";
            resourceInputs["htmlUrl"] = (args?.htmlUrl) ?? "https://github.com";
            resourceInputs["installationId"] = args?.installationId;
            resourceInputs["isSystemWide"] = args?.isSystemWide;
            resourceInputs["name"] = args?.name;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["privateKeyUuid"] = args?.privateKeyUuid;
            resourceInputs["webhookSecret"] = args?.webhookSecret ? pulumi.secret(args.webhookSecret) : undefined;
            resourceInputs["internalId"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["apiUrl"] = undefined /*out*/;
            resourceInputs["appId"] = undefined /*out*/;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["customPort"] = undefined /*out*/;
            resourceInputs["customUser"] = undefined /*out*/;
            resourceInputs["htmlUrl"] = undefined /*out*/;
            resourceInputs["installationId"] = undefined /*out*/;
            resourceInputs["internalId"] = undefined /*out*/;
            resourceInputs["isSystemWide"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["organization"] = undefined /*out*/;
            resourceInputs["privateKeyUuid"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
            resourceInputs["webhookSecret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret", "webhookSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GitHubApp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a GitHubApp resource.
 */
export interface GitHubAppArgs {
    /**
     * GitHub API URL. Derived from htmlUrl when unset.
     */
    apiUrl?: pulumi.Input<string | undefined>;
    /**
     * Numeric GitHub App ID.
     */
    appId: pulumi.Input<number>;
    /**
     * OAuth client ID of the app.
     */
    clientId: pulumi.Input<string>;
    /**
     * OAuth client secret of the app.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * SSH port for git operations.
     */
    customPort?: pulumi.Input<number | undefined>;
    /**
     * SSH user for git operations.
     */
    customUser?: pulumi.Input<string | undefined>;
    /**
     * GitHub web URL.
     */
    htmlUrl?: pulumi.Input<string | undefined>;
    /**
     * Installation ID of the app in the organization or account.
     */
    installationId: pulumi.Input<number>;
    /**
     * Make the app available to all teams (self-hosted only).
     */
    isSystemWide?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the GitHub App in Coolify. An existing app with this name is adopted.
     */
    name: pulumi.Input<string>;
    /**
     * GitHub organization the app is installed in. Leave unset for a personal account.
     */
    organization?: pulumi.Input<string | undefined>;
    /**
     * UUID of the Coolify private key holding the app's private key (the uuid output of a PrivateKey resource).
     */
    privateKeyUuid: pulumi.Input<string>;
    /**
     * Webhook secret of the app.
     */
    webhookSecret?: pulumi.Input<string | undefined>;
}
