// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApplicationArgs } from "./application";
export type Application = import("./application").Application;
export const Application: typeof import("./application").Application = null as any;
utilities.lazyLoad(exports, ["Application"], () => require("./application"));

export { DatabaseArgs } from "./database";
export type Database = import("./database").Database;
export const Database: typeof import("./database").Database = null as any;
utilities.lazyLoad(exports, ["Database"], () => require("./database"));

export { DatabaseBackupArgs } from "./databaseBackup";
export type DatabaseBackup = import("./databaseBackup").DatabaseBackup;
export const DatabaseBackup: typeof import("./databaseBackup").DatabaseBackup = null as any;
utilities.lazyLoad(exports, ["DatabaseBackup"], () => require("./databaseBackup"));

export { DeploymentArgs } from "./deployment";
export type Deployment = import("./deployment").Deployment;
export const Deployment: typeof import("./deployment").Deployment = null as any;
utilities.lazyLoad(exports, ["Deployment"], () => require("./deployment"));

export { GetStorageArgs, GetStorageResult, GetStorageOutputArgs } from "./getStorage";
export const getStorage: typeof import("./getStorage").getStorage = null as any;
export const getStorageOutput: typeof import("./getStorage").getStorageOutput = null as any;
utilities.lazyLoad(exports, ["getStorage","getStorageOutput"], () => require("./getStorage"));

export { GitHubAppArgs } from "./gitHubApp";
export type GitHubApp = import("./gitHubApp").GitHubApp;
export const GitHubApp: typeof import("./gitHubApp").GitHubApp = null as any;
utilities.lazyLoad(exports, ["GitHubApp"], () => require("./gitHubApp"));

export { NotificationDiscordArgs } from "./notificationDiscord";
export type NotificationDiscord = import("./notificationDiscord").NotificationDiscord;
export const NotificationDiscord: typeof import("./notificationDiscord").NotificationDiscord = null as any;
utilities.lazyLoad(exports, ["NotificationDiscord"], () => require("./notificationDiscord"));

export { NotificationEmailArgs } from "./notificationEmail";
export type NotificationEmail = import("./notificationEmail").NotificationEmail;
export const NotificationEmail: typeof import("./notificationEmail").NotificationEmail = null as any;
utilities.lazyLoad(exports, ["NotificationEmail"], () => require("./notificationEmail"));

export { NotificationPushoverArgs } from "./notificationPushover";
export type NotificationPushover = import("./notificationPushover").NotificationPushover;
export const NotificationPushover: typeof import("./notificationPushover").NotificationPushover = null as any;
utilities.lazyLoad(exports, ["NotificationPushover"], () => require("./notificationPushover"));

export { NotificationSlackArgs } from "./notificationSlack";
export type NotificationSlack = import("./notificationSlack").NotificationSlack;
export const NotificationSlack: typeof import("./notificationSlack").NotificationSlack = null as any;
utilities.lazyLoad(exports, ["NotificationSlack"], () => require("./notificationSlack"));

export { NotificationTelegramArgs } from "./notificationTelegram";
export type NotificationTelegram = import("./notificationTelegram").NotificationTelegram;
export const NotificationTelegram: typeof import("./notificationTelegram").NotificationTelegram = null as any;
utilities.lazyLoad(exports, ["NotificationTelegram"], () => require("./notificationTelegram"));

export { NotificationWebhookArgs } from "./notificationWebhook";
export type NotificationWebhook = import("./notificationWebhook").NotificationWebhook;
export const NotificationWebhook: typeof import("./notificationWebhook").NotificationWebhook = null as any;
utilities.lazyLoad(exports, ["NotificationWebhook"], () => require("./notificationWebhook"));

export { PrivateKeyArgs } from "./privateKey";
export type PrivateKey = import("./privateKey").PrivateKey;
export const PrivateKey: typeof import("./privateKey").PrivateKey = null as any;
utilities.lazyLoad(exports, ["PrivateKey"], () => require("./privateKey"));

export { ProjectArgs } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { S3StorageArgs } from "./s3storage";
export type S3Storage = import("./s3storage").S3Storage;
export const S3Storage: typeof import("./s3storage").S3Storage = null as any;
utilities.lazyLoad(exports, ["S3Storage"], () => require("./s3storage"));

export { ScheduledTaskArgs } from "./scheduledTask";
export type ScheduledTask = import("./scheduledTask").ScheduledTask;
export const ScheduledTask: typeof import("./scheduledTask").ScheduledTask = null as any;
utilities.lazyLoad(exports, ["ScheduledTask"], () => require("./scheduledTask"));

export { ServerArgs } from "./server";
export type Server = import("./server").Server;
export const Server: typeof import("./server").Server = null as any;
utilities.lazyLoad(exports, ["Server"], () => require("./server"));

export { ServiceArgs } from "./service";
export type Service = import("./service").Service;
export const Service: typeof import("./service").Service = null as any;
utilities.lazyLoad(exports, ["Service"], () => require("./service"));

export { StorageArgs } from "./storage";
export type Storage = import("./storage").Storage;
export const Storage: typeof import("./storage").Storage = null as any;
utilities.lazyLoad(exports, ["Storage"], () => require("./storage"));

export { VolumeBackupArgs } from "./volumeBackup";
export type VolumeBackup = import("./volumeBackup").VolumeBackup;
export const VolumeBackup: typeof import("./volumeBackup").VolumeBackup = null as any;
utilities.lazyLoad(exports, ["VolumeBackup"], () => require("./volumeBackup"));


// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "coolify:index:Application":
                return new Application(name, <any>undefined, { urn })
            case "coolify:index:Database":
                return new Database(name, <any>undefined, { urn })
            case "coolify:index:DatabaseBackup":
                return new DatabaseBackup(name, <any>undefined, { urn })
            case "coolify:index:Deployment":
                return new Deployment(name, <any>undefined, { urn })
            case "coolify:index:GitHubApp":
                return new GitHubApp(name, <any>undefined, { urn })
            case "coolify:index:NotificationDiscord":
                return new NotificationDiscord(name, <any>undefined, { urn })
            case "coolify:index:NotificationEmail":
                return new NotificationEmail(name, <any>undefined, { urn })
            case "coolify:index:NotificationPushover":
                return new NotificationPushover(name, <any>undefined, { urn })
            case "coolify:index:NotificationSlack":
                return new NotificationSlack(name, <any>undefined, { urn })
            case "coolify:index:NotificationTelegram":
                return new NotificationTelegram(name, <any>undefined, { urn })
            case "coolify:index:NotificationWebhook":
                return new NotificationWebhook(name, <any>undefined, { urn })
            case "coolify:index:PrivateKey":
                return new PrivateKey(name, <any>undefined, { urn })
            case "coolify:index:Project":
                return new Project(name, <any>undefined, { urn })
            case "coolify:index:S3Storage":
                return new S3Storage(name, <any>undefined, { urn })
            case "coolify:index:ScheduledTask":
                return new ScheduledTask(name, <any>undefined, { urn })
            case "coolify:index:Server":
                return new Server(name, <any>undefined, { urn })
            case "coolify:index:Service":
                return new Service(name, <any>undefined, { urn })
            case "coolify:index:Storage":
                return new Storage(name, <any>undefined, { urn })
            case "coolify:index:VolumeBackup":
                return new VolumeBackup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("coolify", "index", _module)
pulumi.runtime.registerResourcePackage("coolify", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:coolify") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
