// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApplicationArgs } from "./application";
export type Application = import("./application").Application;
export const Application: typeof import("./application").Application = null as any;
utilities.lazyLoad(exports, ["Application"], () => require("./application"));

export { DatabaseArgs } from "./database";
export type Database = import("./database").Database;
export const Database: typeof import("./database").Database = null as any;
utilities.lazyLoad(exports, ["Database"], () => require("./database"));

export { DeploymentArgs } from "./deployment";
export type Deployment = import("./deployment").Deployment;
export const Deployment: typeof import("./deployment").Deployment = null as any;
utilities.lazyLoad(exports, ["Deployment"], () => require("./deployment"));

export { PrivateKeyArgs } from "./privateKey";
export type PrivateKey = import("./privateKey").PrivateKey;
export const PrivateKey: typeof import("./privateKey").PrivateKey = null as any;
utilities.lazyLoad(exports, ["PrivateKey"], () => require("./privateKey"));

export { ProjectArgs } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { S3StorageArgs } from "./s3storage";
export type S3Storage = import("./s3storage").S3Storage;
export const S3Storage: typeof import("./s3storage").S3Storage = null as any;
utilities.lazyLoad(exports, ["S3Storage"], () => require("./s3storage"));

export { ServerArgs } from "./server";
export type Server = import("./server").Server;
export const Server: typeof import("./server").Server = null as any;
utilities.lazyLoad(exports, ["Server"], () => require("./server"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "coolify:index:Application":
                return new Application(name, <any>undefined, { urn })
            case "coolify:index:Database":
                return new Database(name, <any>undefined, { urn })
            case "coolify:index:Deployment":
                return new Deployment(name, <any>undefined, { urn })
            case "coolify:index:PrivateKey":
                return new PrivateKey(name, <any>undefined, { urn })
            case "coolify:index:Project":
                return new Project(name, <any>undefined, { urn })
            case "coolify:index:S3Storage":
                return new S3Storage(name, <any>undefined, { urn })
            case "coolify:index:Server":
                return new Server(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("coolify", "index", _module)
pulumi.runtime.registerResourcePackage("coolify", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:coolify") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
