// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Pushover push notifications. Manages one settings object per API token team on Coolify v4.3.0+. Create adopts existing settings. Only declared fields are changed. Delete disables delivery and retains credentials and event choices.
 */
export class NotificationPushover extends pulumi.CustomResource {
    /**
     * Get an existing NotificationPushover resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NotificationPushover {
        return new NotificationPushover(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:NotificationPushover';

    /**
     * Returns true if the given object is an instance of NotificationPushover.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationPushover {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationPushover.__pulumiType;
    }

    /**
     * pushover api token. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly apiToken: pulumi.Output<string | undefined>;
    /**
     * pushover enabled. Omit to leave the current setting unmanaged.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    declare public readonly events: pulumi.Output<outputs.NotificationEvents | undefined>;
    /**
     * The Coolify team ID derived from the provider's API token. Import using <teamId>/pushover.
     */
    declare public /*out*/ readonly teamId: pulumi.Output<number>;
    /**
     * pushover user key. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly userKey: pulumi.Output<string | undefined>;

    /**
     * Create a NotificationPushover resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NotificationPushoverArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiToken"] = args?.apiToken ? pulumi.secret(args.apiToken) : undefined;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["events"] = args?.events;
            resourceInputs["userKey"] = args?.userKey ? pulumi.secret(args.userKey) : undefined;
            resourceInputs["teamId"] = undefined /*out*/;
        } else {
            resourceInputs["apiToken"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["events"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["userKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiToken", "userKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NotificationPushover.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NotificationPushover resource.
 */
export interface NotificationPushoverArgs {
    /**
     * pushover api token. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    apiToken?: pulumi.Input<string | undefined>;
    /**
     * pushover enabled. Omit to leave the current setting unmanaged.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    events?: pulumi.Input<inputs.NotificationEventsArgs | undefined>;
    /**
     * pushover user key. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    userKey?: pulumi.Input<string | undefined>;
}
