// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Slack-compatible notifications, including Mattermost incoming webhooks. Manages one settings object per API token team on Coolify v4.3.0+. Create adopts existing settings. Only declared fields are changed. Delete disables delivery and retains credentials and event choices.
 */
export class NotificationSlack extends pulumi.CustomResource {
    /**
     * Get an existing NotificationSlack resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NotificationSlack {
        return new NotificationSlack(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:NotificationSlack';

    /**
     * Returns true if the given object is an instance of NotificationSlack.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationSlack {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationSlack.__pulumiType;
    }

    /**
     * slack enabled. Omit to leave the current setting unmanaged.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    declare public readonly events: pulumi.Output<outputs.NotificationEvents | undefined>;
    /**
     * The Coolify team ID derived from the provider's API token. Import using <teamId>/slack.
     */
    declare public /*out*/ readonly teamId: pulumi.Output<number>;
    /**
     * slack webhook url. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly webhookUrl: pulumi.Output<string | undefined>;

    /**
     * Create a NotificationSlack resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NotificationSlackArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["events"] = args?.events;
            resourceInputs["webhookUrl"] = args?.webhookUrl ? pulumi.secret(args.webhookUrl) : undefined;
            resourceInputs["teamId"] = undefined /*out*/;
        } else {
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["events"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["webhookUrl"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NotificationSlack.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NotificationSlack resource.
 */
export interface NotificationSlackArgs {
    /**
     * slack enabled. Omit to leave the current setting unmanaged.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    events?: pulumi.Input<inputs.NotificationEventsArgs | undefined>;
    /**
     * slack webhook url. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    webhookUrl?: pulumi.Input<string | undefined>;
}
