// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Team email notifications through SMTP, Resend or instance email settings. Manages one settings object per API token team on Coolify v4.3.0+. Create adopts existing settings. Only declared fields are changed. Delete disables delivery and retains credentials and event choices.
 */
export class NotificationEmail extends pulumi.CustomResource {
    /**
     * Get an existing NotificationEmail resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NotificationEmail {
        return new NotificationEmail(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:NotificationEmail';

    /**
     * Returns true if the given object is an instance of NotificationEmail.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationEmail {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationEmail.__pulumiType;
    }

    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    declare public readonly events: pulumi.Output<outputs.NotificationEvents | undefined>;
    /**
     * resend api key. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly resendApiKey: pulumi.Output<string | undefined>;
    /**
     * resend enabled. Omit to leave the current setting unmanaged.
     */
    declare public readonly resendEnabled: pulumi.Output<boolean | undefined>;
    /**
     * smtp ehlo domain. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpEhloDomain: pulumi.Output<string | undefined>;
    /**
     * smtp enabled. Omit to leave the current setting unmanaged.
     */
    declare public readonly smtpEnabled: pulumi.Output<boolean | undefined>;
    /**
     * SMTP transport encryption: starttls, tls or none. Omit to leave the current setting unmanaged.
     */
    declare public readonly smtpEncryption: pulumi.Output<enums.NotificationSMTPEncryption | undefined>;
    /**
     * smtp from address. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpFromAddress: pulumi.Output<string | undefined>;
    /**
     * smtp from name. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpFromName: pulumi.Output<string | undefined>;
    /**
     * smtp host. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpHost: pulumi.Output<string | undefined>;
    /**
     * smtp password. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpPassword: pulumi.Output<string | undefined>;
    /**
     * smtp port. Omit to leave the current setting unmanaged.
     */
    declare public readonly smtpPort: pulumi.Output<number | undefined>;
    /**
     * smtp recipients. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpRecipients: pulumi.Output<string | undefined>;
    /**
     * smtp timeout. Omit to leave the current setting unmanaged.
     */
    declare public readonly smtpTimeout: pulumi.Output<number | undefined>;
    /**
     * smtp username. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    declare public readonly smtpUsername: pulumi.Output<string | undefined>;
    /**
     * The Coolify team ID derived from the provider's API token. Import using <teamId>/email.
     */
    declare public /*out*/ readonly teamId: pulumi.Output<number>;
    /**
     * use instance email settings. Omit to leave the current setting unmanaged.
     */
    declare public readonly useInstanceEmailSettings: pulumi.Output<boolean | undefined>;

    /**
     * Create a NotificationEmail resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NotificationEmailArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["events"] = args?.events;
            resourceInputs["resendApiKey"] = args?.resendApiKey ? pulumi.secret(args.resendApiKey) : undefined;
            resourceInputs["resendEnabled"] = args?.resendEnabled;
            resourceInputs["smtpEhloDomain"] = args?.smtpEhloDomain;
            resourceInputs["smtpEnabled"] = args?.smtpEnabled;
            resourceInputs["smtpEncryption"] = args?.smtpEncryption;
            resourceInputs["smtpFromAddress"] = args?.smtpFromAddress ? pulumi.secret(args.smtpFromAddress) : undefined;
            resourceInputs["smtpFromName"] = args?.smtpFromName ? pulumi.secret(args.smtpFromName) : undefined;
            resourceInputs["smtpHost"] = args?.smtpHost ? pulumi.secret(args.smtpHost) : undefined;
            resourceInputs["smtpPassword"] = args?.smtpPassword ? pulumi.secret(args.smtpPassword) : undefined;
            resourceInputs["smtpPort"] = args?.smtpPort;
            resourceInputs["smtpRecipients"] = args?.smtpRecipients ? pulumi.secret(args.smtpRecipients) : undefined;
            resourceInputs["smtpTimeout"] = args?.smtpTimeout;
            resourceInputs["smtpUsername"] = args?.smtpUsername ? pulumi.secret(args.smtpUsername) : undefined;
            resourceInputs["useInstanceEmailSettings"] = args?.useInstanceEmailSettings;
            resourceInputs["teamId"] = undefined /*out*/;
        } else {
            resourceInputs["events"] = undefined /*out*/;
            resourceInputs["resendApiKey"] = undefined /*out*/;
            resourceInputs["resendEnabled"] = undefined /*out*/;
            resourceInputs["smtpEhloDomain"] = undefined /*out*/;
            resourceInputs["smtpEnabled"] = undefined /*out*/;
            resourceInputs["smtpEncryption"] = undefined /*out*/;
            resourceInputs["smtpFromAddress"] = undefined /*out*/;
            resourceInputs["smtpFromName"] = undefined /*out*/;
            resourceInputs["smtpHost"] = undefined /*out*/;
            resourceInputs["smtpPassword"] = undefined /*out*/;
            resourceInputs["smtpPort"] = undefined /*out*/;
            resourceInputs["smtpRecipients"] = undefined /*out*/;
            resourceInputs["smtpTimeout"] = undefined /*out*/;
            resourceInputs["smtpUsername"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
            resourceInputs["useInstanceEmailSettings"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["resendApiKey", "smtpFromAddress", "smtpFromName", "smtpHost", "smtpPassword", "smtpRecipients", "smtpUsername"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NotificationEmail.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NotificationEmail resource.
 */
export interface NotificationEmailArgs {
    /**
     * Events delivered through this channel. Only explicitly set event flags are managed.
     */
    events?: pulumi.Input<inputs.NotificationEventsArgs | undefined>;
    /**
     * resend api key. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    resendApiKey?: pulumi.Input<string | undefined>;
    /**
     * resend enabled. Omit to leave the current setting unmanaged.
     */
    resendEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * smtp ehlo domain. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpEhloDomain?: pulumi.Input<string | undefined>;
    /**
     * smtp enabled. Omit to leave the current setting unmanaged.
     */
    smtpEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * SMTP transport encryption: starttls, tls or none. Omit to leave the current setting unmanaged.
     */
    smtpEncryption?: pulumi.Input<enums.NotificationSMTPEncryption | undefined>;
    /**
     * smtp from address. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpFromAddress?: pulumi.Input<string | undefined>;
    /**
     * smtp from name. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpFromName?: pulumi.Input<string | undefined>;
    /**
     * smtp host. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpHost?: pulumi.Input<string | undefined>;
    /**
     * smtp password. Treated as a Pulumi secret. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpPassword?: pulumi.Input<string | undefined>;
    /**
     * smtp port. Omit to leave the current setting unmanaged.
     */
    smtpPort?: pulumi.Input<number | undefined>;
    /**
     * smtp recipients. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpRecipients?: pulumi.Input<string | undefined>;
    /**
     * smtp timeout. Omit to leave the current setting unmanaged.
     */
    smtpTimeout?: pulumi.Input<number | undefined>;
    /**
     * smtp username. Omit to leave the current setting unmanaged. An empty string clears the setting.
     */
    smtpUsername?: pulumi.Input<string | undefined>;
    /**
     * use instance email settings. Omit to leave the current setting unmanaged.
     */
    useInstanceEmailSettings?: pulumi.Input<boolean | undefined>;
}
