// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Coolify SSH private key. An existing key with the same name is adopted on create. Coolify's API cannot update keys, so changing the name or key material replaces the key.
 */
export class PrivateKey extends pulumi.CustomResource {
    /**
     * Get an existing PrivateKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PrivateKey {
        return new PrivateKey(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:PrivateKey';

    /**
     * Returns true if the given object is an instance of PrivateKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrivateKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrivateKey.__pulumiType;
    }

    /**
     * Description of the private key. Applied on create only, because Coolify's API cannot update keys.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Fingerprint of the key.
     */
    declare public /*out*/ readonly fingerprint: pulumi.Output<string>;
    /**
     * Name of the private key. An existing key with this name is adopted. Changing it replaces the key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * PEM encoded private key material. Required to create a key that does not exist yet; adopted keys can be managed without it. Changing it replaces the key.
     */
    declare public readonly privateKey: pulumi.Output<string | undefined>;
    /**
     * Public key derived from the private key.
     */
    declare public /*out*/ readonly publicKey: pulumi.Output<string>;
    /**
     * UUID of the private key in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a PrivateKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PrivateKeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["privateKey"] = args?.privateKey ? pulumi.secret(args.privateKey) : undefined;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["privateKey"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["privateKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(PrivateKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PrivateKey resource.
 */
export interface PrivateKeyArgs {
    /**
     * Description of the private key. Applied on create only, because Coolify's API cannot update keys.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the private key. An existing key with this name is adopted. Changing it replaces the key.
     */
    name: pulumi.Input<string>;
    /**
     * PEM encoded private key material. Required to create a key that does not exist yet; adopted keys can be managed without it. Changing it replaces the key.
     */
    privateKey?: pulumi.Input<string | undefined>;
}
