// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Coolify S3-compatible storage destination, e.g. an R2 bucket for backups.
 */
export class S3Storage extends pulumi.CustomResource {
    /**
     * Get an existing S3Storage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): S3Storage {
        return new S3Storage(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:S3Storage';

    /**
     * Returns true if the given object is an instance of S3Storage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is S3Storage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === S3Storage.__pulumiType;
    }

    declare public readonly bucket: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly endpoint: pulumi.Output<string>;
    /**
     * Whether Coolify validated the storage as usable.
     */
    declare public /*out*/ readonly isUsable: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly region: pulumi.Output<string>;
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a S3Storage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: S3StorageArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accessKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'accessKey'");
            }
            if (args?.bucket === undefined && !opts.urn) {
                throw new Error("Missing required property 'bucket'");
            }
            if (args?.endpoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.secretKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretKey'");
            }
            resourceInputs["accessKey"] = args?.accessKey ? pulumi.secret(args.accessKey) : undefined;
            resourceInputs["bucket"] = args?.bucket;
            resourceInputs["description"] = args?.description;
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["secretKey"] = args?.secretKey ? pulumi.secret(args.secretKey) : undefined;
            resourceInputs["isUsable"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["bucket"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["isUsable"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(S3Storage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a S3Storage resource.
 */
export interface S3StorageArgs {
    /**
     * S3 access key. Never stored in state.
     */
    accessKey: pulumi.Input<string>;
    bucket: pulumi.Input<string>;
    description?: pulumi.Input<string | undefined>;
    endpoint: pulumi.Input<string>;
    name: pulumi.Input<string>;
    region?: pulumi.Input<string | undefined>;
    /**
     * S3 secret key. Never stored in state.
     */
    secretKey: pulumi.Input<string>;
}
