// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A scheduled task (cron job) on a Coolify application. An existing task with the same name on the application is adopted on create.
 */
export class ScheduledTask extends pulumi.CustomResource {
    /**
     * Get an existing ScheduledTask resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ScheduledTask {
        return new ScheduledTask(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:ScheduledTask';

    /**
     * Returns true if the given object is an instance of ScheduledTask.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ScheduledTask {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ScheduledTask.__pulumiType;
    }

    /**
     * UUID of the Coolify application the task runs on (the uuid output of an Application resource).
     */
    declare public readonly applicationUuid: pulumi.Output<string>;
    /**
     * Command to execute.
     */
    declare public readonly command: pulumi.Output<string>;
    /**
     * Container to run the command in. Defaults to the application's container.
     */
    declare public readonly container: pulumi.Output<string | undefined>;
    /**
     * Whether the task is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Cron expression or Coolify shorthand such as "daily", "hourly" or "@every 5m".
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Name of the task. An existing task with this name on the application is adopted.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Timeout in seconds. Leave unset to keep Coolify's default.
     */
    declare public readonly timeout: pulumi.Output<number | undefined>;
    /**
     * UUID of the task in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a ScheduledTask resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScheduledTaskArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.applicationUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicationUuid'");
            }
            if (args?.command === undefined && !opts.urn) {
                throw new Error("Missing required property 'command'");
            }
            if (args?.frequency === undefined && !opts.urn) {
                throw new Error("Missing required property 'frequency'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["applicationUuid"] = args?.applicationUuid;
            resourceInputs["command"] = args?.command;
            resourceInputs["container"] = args?.container;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["name"] = args?.name;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["applicationUuid"] = undefined /*out*/;
            resourceInputs["command"] = undefined /*out*/;
            resourceInputs["container"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["frequency"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["timeout"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ScheduledTask.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ScheduledTask resource.
 */
export interface ScheduledTaskArgs {
    /**
     * UUID of the Coolify application the task runs on (the uuid output of an Application resource).
     */
    applicationUuid: pulumi.Input<string>;
    /**
     * Command to execute.
     */
    command: pulumi.Input<string>;
    /**
     * Container to run the command in. Defaults to the application's container.
     */
    container?: pulumi.Input<string | undefined>;
    /**
     * Whether the task is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Cron expression or Coolify shorthand such as "daily", "hourly" or "@every 5m".
     */
    frequency: pulumi.Input<string>;
    /**
     * Name of the task. An existing task with this name on the application is adopted.
     */
    name: pulumi.Input<string>;
    /**
     * Timeout in seconds. Leave unset to keep Coolify's default.
     */
    timeout?: pulumi.Input<number | undefined>;
}
