// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Queues a Coolify service restart on create and when triggers change. Coolify recreates the configured containers asynchronously and may briefly interrupt service. Completion acknowledges the request only; it does not verify deployment completion or health. Deleting this resource leaves the service running.
 */
export class ServiceDeployment extends pulumi.CustomResource {
    /**
     * Get an existing ServiceDeployment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ServiceDeployment {
        return new ServiceDeployment(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:ServiceDeployment';

    /**
     * Returns true if the given object is an instance of ServiceDeployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceDeployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceDeployment.__pulumiType;
    }

    /**
     * UUID of the Coolify service to redeploy (the uuid output of a Service resource). Changing it replaces this request resource. Declare at most one ServiceDeployment for each service.
     */
    declare public readonly service: pulumi.Output<string>;
    /**
     * The last request acknowledgment: queued after Coolify accepts a restart request. This is not the current deployment or health status and is not polled. Empty for imported resources whose request history is unknown.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Values that queue a new restart when changed, such as an image version or configuration digest. Include every configuration change that should redeploy; updating a Service alone does not change these triggers.
     */
    declare public readonly triggers: pulumi.Output<string[] | undefined>;

    /**
     * Create a ServiceDeployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceDeploymentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            resourceInputs["service"] = args?.service;
            resourceInputs["triggers"] = args?.triggers;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["service"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["triggers"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceDeployment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ServiceDeployment resource.
 */
export interface ServiceDeploymentArgs {
    /**
     * UUID of the Coolify service to redeploy (the uuid output of a Service resource). Changing it replaces this request resource. Declare at most one ServiceDeployment for each service.
     */
    service: pulumi.Input<string>;
    /**
     * Values that queue a new restart when changed, such as an image version or configuration digest. Include every configuration change that should redeploy; updating a Service alone does not change these triggers.
     */
    triggers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
