// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Coolify service from a one-click template or a docker compose file. An existing service with the same name in the environment is adopted on create.
 */
export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * Tags the provider attached: the provider's default tags plus the declared ones.
     */
    declare public /*out*/ readonly appliedTags: pulumi.Output<string[] | undefined>;
    /**
     * Connect the service to Coolify's predefined Docker network.
     */
    declare public readonly connectToDockerNetwork: pulumi.Output<boolean | undefined>;
    /**
     * Description of the service.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * UUID of the destination when the server has several. Only relevant on create.
     */
    declare public readonly destinationUuid: pulumi.Output<string | undefined>;
    /**
     * Docker compose file content for custom services. Exactly one of type and dockerCompose must be set. Coolify does not report the compose file back, so drift on this input is not detected.
     */
    declare public readonly dockerCompose: pulumi.Output<string | undefined>;
    /**
     * Name of the environment inside the project. Changing it moves the service in place; the environment must already exist.
     */
    declare public readonly environmentName: pulumi.Output<string>;
    /**
     * Environment variables managed by key. Declared keys missing in Coolify are created as hidden values; existing keys are never patched and undeclared keys are left untouched.
     */
    declare public readonly environmentVariables: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Start the service right after creating it. Only relevant on create.
     */
    declare public readonly instantDeploy: pulumi.Output<boolean | undefined>;
    /**
     * Service name. Defaults to the Pulumi resource name. An existing service with this name in the environment is adopted.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * UUID of the Coolify project (the uuid output of a Project resource). Changing it moves the service to the new project in place.
     */
    declare public readonly projectUuid: pulumi.Output<string>;
    /**
     * UUID of the server hosting the service (the uuid output of a Server resource). Changing it replaces the service.
     */
    declare public readonly serverUuid: pulumi.Output<string>;
    /**
     * Tags attached to the service in addition to the provider's default tags. Declared tags are attached, tags removed from the declaration are detached, tags added in the Coolify UI are left untouched.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * One-click service type, e.g. "plausible" or "gitea-with-mysql". Exactly one of type and dockerCompose must be set. Changing it replaces the service.
     */
    declare public readonly type: pulumi.Output<string | undefined>;
    /**
     * UUID of the service in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentName === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentName'");
            }
            if (args?.projectUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectUuid'");
            }
            if (args?.serverUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverUuid'");
            }
            resourceInputs["connectToDockerNetwork"] = args?.connectToDockerNetwork;
            resourceInputs["description"] = args?.description;
            resourceInputs["destinationUuid"] = args?.destinationUuid;
            resourceInputs["dockerCompose"] = args?.dockerCompose;
            resourceInputs["environmentName"] = args?.environmentName;
            resourceInputs["environmentVariables"] = args?.environmentVariables;
            resourceInputs["instantDeploy"] = args?.instantDeploy;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectUuid"] = args?.projectUuid;
            resourceInputs["serverUuid"] = args?.serverUuid;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["type"] = args?.type;
            resourceInputs["appliedTags"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["appliedTags"] = undefined /*out*/;
            resourceInputs["connectToDockerNetwork"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["destinationUuid"] = undefined /*out*/;
            resourceInputs["dockerCompose"] = undefined /*out*/;
            resourceInputs["environmentName"] = undefined /*out*/;
            resourceInputs["environmentVariables"] = undefined /*out*/;
            resourceInputs["instantDeploy"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["projectUuid"] = undefined /*out*/;
            resourceInputs["serverUuid"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Service.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * Connect the service to Coolify's predefined Docker network.
     */
    connectToDockerNetwork?: pulumi.Input<boolean | undefined>;
    /**
     * Description of the service.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * UUID of the destination when the server has several. Only relevant on create.
     */
    destinationUuid?: pulumi.Input<string | undefined>;
    /**
     * Docker compose file content for custom services. Exactly one of type and dockerCompose must be set. Coolify does not report the compose file back, so drift on this input is not detected.
     */
    dockerCompose?: pulumi.Input<string | undefined>;
    /**
     * Name of the environment inside the project. Changing it moves the service in place; the environment must already exist.
     */
    environmentName: pulumi.Input<string>;
    /**
     * Environment variables managed by key. Declared keys missing in Coolify are created as hidden values; existing keys are never patched and undeclared keys are left untouched.
     */
    environmentVariables?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Start the service right after creating it. Only relevant on create.
     */
    instantDeploy?: pulumi.Input<boolean | undefined>;
    /**
     * Service name. Defaults to the Pulumi resource name. An existing service with this name in the environment is adopted.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * UUID of the Coolify project (the uuid output of a Project resource). Changing it moves the service to the new project in place.
     */
    projectUuid: pulumi.Input<string>;
    /**
     * UUID of the server hosting the service (the uuid output of a Server resource). Changing it replaces the service.
     */
    serverUuid: pulumi.Input<string>;
    /**
     * Tags attached to the service in addition to the provider's default tags. Declared tags are attached, tags removed from the declaration are detached, tags added in the Coolify UI are left untouched.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * One-click service type, e.g. "plausible" or "gitea-with-mysql". Exactly one of type and dockerCompose must be set. Changing it replaces the service.
     */
    type?: pulumi.Input<string | undefined>;
}
