// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Coolify server connected over SSH with a Coolify private key.
 */
export class Server extends pulumi.CustomResource {
    /**
     * Get an existing Server resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Server {
        return new Server(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Server';

    /**
     * Returns true if the given object is an instance of Server.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Server {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Server.__pulumiType;
    }

    declare public readonly description: pulumi.Output<string>;
    declare public readonly ip: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly port: pulumi.Output<number>;
    declare public readonly privateKeyUuid: pulumi.Output<string>;
    declare public readonly user: pulumi.Output<string>;
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Server resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.ip === undefined && !opts.urn) {
                throw new Error("Missing required property 'ip'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.privateKeyUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'privateKeyUuid'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["ip"] = args?.ip;
            resourceInputs["name"] = args?.name;
            resourceInputs["port"] = args?.port;
            resourceInputs["privateKeyUuid"] = args?.privateKeyUuid;
            resourceInputs["user"] = args?.user;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["privateKeyUuid"] = undefined /*out*/;
            resourceInputs["user"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Server.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Server resource.
 */
export interface ServerArgs {
    description?: pulumi.Input<string | undefined>;
    ip: pulumi.Input<string>;
    name: pulumi.Input<string>;
    port?: pulumi.Input<number | undefined>;
    /**
     * UUID of the Coolify private key used to connect. Usually the id output of a PrivateKey resource.
     */
    privateKeyUuid: pulumi.Input<string>;
    user?: pulumi.Input<string | undefined>;
}
