// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A persistent volume or directory mount of a Coolify application or database. An existing storage with the same mount path on the owner is adopted on create. Volumes declared in a docker compose file are managed by Coolify itself and cannot be created here; look them up with getStorage instead.
 */
export class Storage extends pulumi.CustomResource {
    /**
     * Get an existing Storage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Storage {
        return new Storage(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:Storage';

    /**
     * Returns true if the given object is an instance of Storage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Storage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Storage.__pulumiType;
    }

    /**
     * UUID of the application the storage is mounted into. Exactly one of applicationUuid and databaseUuid must be set. Changing it replaces the storage.
     */
    declare public readonly applicationUuid: pulumi.Output<string | undefined>;
    /**
     * UUID of the database the storage is mounted into. Exactly one of applicationUuid and databaseUuid must be set. Changing it replaces the storage.
     */
    declare public readonly databaseUuid: pulumi.Output<string | undefined>;
    /**
     * Host directory for directory storages. Required for directory storages; changing it replaces the storage.
     */
    declare public readonly fsPath: pulumi.Output<string | undefined>;
    /**
     * Host path to bind a persistent volume to. Leave unset for a plain Docker volume.
     */
    declare public readonly hostPath: pulumi.Output<string | undefined>;
    /**
     * Add a -pr-N suffix for preview deployments.
     */
    declare public readonly isPreviewSuffixEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Container mount path. An existing storage with this mount path on the owner is adopted on create.
     */
    declare public readonly mountPath: pulumi.Output<string>;
    /**
     * Volume name for persistent storages, without the owner prefix Coolify adds. Required for persistent storages.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * Kind of storage. Changing it replaces the storage.
     */
    declare public readonly type: pulumi.Output<enums.StorageType>;
    /**
     * UUID of the storage in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * Full volume name as reported by Coolify, including the owner prefix.
     */
    declare public /*out*/ readonly volumeName: pulumi.Output<string>;

    /**
     * Create a Storage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StorageArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.mountPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'mountPath'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["applicationUuid"] = args?.applicationUuid;
            resourceInputs["databaseUuid"] = args?.databaseUuid;
            resourceInputs["fsPath"] = args?.fsPath;
            resourceInputs["hostPath"] = args?.hostPath;
            resourceInputs["isPreviewSuffixEnabled"] = args?.isPreviewSuffixEnabled;
            resourceInputs["mountPath"] = args?.mountPath;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
            resourceInputs["uuid"] = undefined /*out*/;
            resourceInputs["volumeName"] = undefined /*out*/;
        } else {
            resourceInputs["applicationUuid"] = undefined /*out*/;
            resourceInputs["databaseUuid"] = undefined /*out*/;
            resourceInputs["fsPath"] = undefined /*out*/;
            resourceInputs["hostPath"] = undefined /*out*/;
            resourceInputs["isPreviewSuffixEnabled"] = undefined /*out*/;
            resourceInputs["mountPath"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
            resourceInputs["volumeName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Storage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Storage resource.
 */
export interface StorageArgs {
    /**
     * UUID of the application the storage is mounted into. Exactly one of applicationUuid and databaseUuid must be set. Changing it replaces the storage.
     */
    applicationUuid?: pulumi.Input<string | undefined>;
    /**
     * UUID of the database the storage is mounted into. Exactly one of applicationUuid and databaseUuid must be set. Changing it replaces the storage.
     */
    databaseUuid?: pulumi.Input<string | undefined>;
    /**
     * Host directory for directory storages. Required for directory storages; changing it replaces the storage.
     */
    fsPath?: pulumi.Input<string | undefined>;
    /**
     * Host path to bind a persistent volume to. Leave unset for a plain Docker volume.
     */
    hostPath?: pulumi.Input<string | undefined>;
    /**
     * Add a -pr-N suffix for preview deployments.
     */
    isPreviewSuffixEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Container mount path. An existing storage with this mount path on the owner is adopted on create.
     */
    mountPath: pulumi.Input<string>;
    /**
     * Volume name for persistent storages, without the owner prefix Coolify adds. Required for persistent storages.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Kind of storage. Changing it replaces the storage.
     */
    type: pulumi.Input<enums.StorageType>;
}
