// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A shared variable for the API token's team on Coolify v4.3.0+. Adopts an existing key in this scope and updates declared settings in place. Delete removes the variable. Import using team/<id>; URL-encode path components containing slashes.
 */
export class TeamSharedVariable extends pulumi.CustomResource {
    /**
     * Get an existing TeamSharedVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TeamSharedVariable {
        return new TeamSharedVariable(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:TeamSharedVariable';

    /**
     * Returns true if the given object is an instance of TeamSharedVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TeamSharedVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TeamSharedVariable.__pulumiType;
    }

    /**
     * Optional comment (maximum 256 characters). Omit to leave it unmanaged; an empty string clears it.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Treat the value literally. Omit to preserve the current setting; false explicitly disables it.
     */
    declare public readonly isLiteral: pulumi.Output<boolean | undefined>;
    /**
     * Treat the value as multiline. Omit to preserve the current setting; false explicitly disables it.
     */
    declare public readonly isMultiline: pulumi.Output<boolean | undefined>;
    /**
     * Hide the value from subsequent API reads, even with sensitive-read permission. The API still allows updates. Omit to preserve the current setting.
     */
    declare public readonly isShownOnce: pulumi.Output<boolean | undefined>;
    /**
     * Variable key. An existing variable with this key in the same scope is adopted. Renaming updates it in place.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * Coolify reference such as {{team.KEY}}. Use as a resource environment variable value; the output also establishes a Pulumi dependency. Applying shared variables to running workloads requires redeployment.
     */
    declare public /*out*/ readonly reference: pulumi.Output<string>;
    /**
     * Variable value, stored as a Pulumi secret. Omit to leave it unmanaged; an empty string clears it. Refresh preserves the previous value when Coolify omits it. Reading values requires read:sensitive or root permission.
     */
    declare public readonly value: pulumi.Output<string | undefined>;
    /**
     * Numeric ID of the shared variable in Coolify.
     */
    declare public /*out*/ readonly variableId: pulumi.Output<number>;

    /**
     * Create a TeamSharedVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamSharedVariableArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            resourceInputs["comment"] = args?.comment;
            resourceInputs["isLiteral"] = args?.isLiteral;
            resourceInputs["isMultiline"] = args?.isMultiline;
            resourceInputs["isShownOnce"] = args?.isShownOnce;
            resourceInputs["key"] = args?.key;
            resourceInputs["value"] = args?.value !== undefined ? pulumi.secret(args.value) : undefined;
            resourceInputs["reference"] = undefined /*out*/;
            resourceInputs["variableId"] = undefined /*out*/;
        } else {
            resourceInputs["comment"] = undefined /*out*/;
            resourceInputs["isLiteral"] = undefined /*out*/;
            resourceInputs["isMultiline"] = undefined /*out*/;
            resourceInputs["isShownOnce"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["reference"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
            resourceInputs["variableId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TeamSharedVariable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TeamSharedVariable resource.
 */
export interface TeamSharedVariableArgs {
    /**
     * Optional comment (maximum 256 characters). Omit to leave it unmanaged; an empty string clears it.
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * Treat the value literally. Omit to preserve the current setting; false explicitly disables it.
     */
    isLiteral?: pulumi.Input<boolean | undefined>;
    /**
     * Treat the value as multiline. Omit to preserve the current setting; false explicitly disables it.
     */
    isMultiline?: pulumi.Input<boolean | undefined>;
    /**
     * Hide the value from subsequent API reads, even with sensitive-read permission. The API still allows updates. Omit to preserve the current setting.
     */
    isShownOnce?: pulumi.Input<boolean | undefined>;
    /**
     * Variable key. An existing variable with this key in the same scope is adopted. Renaming updates it in place.
     */
    key: pulumi.Input<string>;
    /**
     * Variable value, stored as a Pulumi secret. Omit to leave it unmanaged; an empty string clears it. Refresh preserves the previous value when Coolify omits it. Reading values requires read:sensitive or root permission.
     */
    value?: pulumi.Input<string | undefined>;
}
