// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The backup schedule of a persistent volume or directory mount of a Coolify application, database or service, archived locally and optionally uploaded to an S3 storage. Each storage has at most one schedule, which is created or replaced as a whole. Coolify offers no endpoint to read a schedule back, so changes made in the Coolify UI are not detected. Destroying the resource deletes the schedule together with all local and S3 archives; use retainOnDelete to keep them.
 */
export class VolumeBackup extends pulumi.CustomResource {
    /**
     * Get an existing VolumeBackup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): VolumeBackup {
        return new VolumeBackup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coolify:index:VolumeBackup';

    /**
     * Returns true if the given object is an instance of VolumeBackup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VolumeBackup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VolumeBackup.__pulumiType;
    }

    /**
     * UUID of the application owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    declare public readonly applicationUuid: pulumi.Output<string | undefined>;
    /**
     * Run a backup right after creating the schedule. Only relevant on create.
     */
    declare public readonly backupNow: pulumi.Output<boolean | undefined>;
    /**
     * UUID of the database owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    declare public readonly databaseUuid: pulumi.Output<string | undefined>;
    /**
     * Keep no local archive once uploaded to S3. Requires saveS3.
     */
    declare public readonly disableLocalBackup: pulumi.Output<boolean | undefined>;
    /**
     * Whether the schedule is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Cron expression or Coolify shorthand such as "daily" or "0 3 * * *".
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Mount path of the storage to back up, resolved on the owner. Exactly one of storageUuid and mountPath must be set. Changing it replaces the schedule.
     */
    declare public readonly mountPath: pulumi.Output<string | undefined>;
    /**
     * UUID of the storage the schedule belongs to.
     */
    declare public /*out*/ readonly resolvedStorageUuid: pulumi.Output<string>;
    /**
     * Number of archives kept locally; 0 keeps all.
     */
    declare public readonly retentionAmountLocally: pulumi.Output<number>;
    /**
     * Number of archives kept in S3; 0 keeps all.
     */
    declare public readonly retentionAmountS3: pulumi.Output<number>;
    /**
     * Days local archives are kept; 0 keeps them forever.
     */
    declare public readonly retentionDaysLocally: pulumi.Output<number | undefined>;
    /**
     * Days S3 archives are kept; 0 keeps them forever.
     */
    declare public readonly retentionDaysS3: pulumi.Output<number | undefined>;
    /**
     * Maximum local storage in GB; 0 is unlimited.
     */
    declare public readonly retentionMaxStorageLocally: pulumi.Output<number | undefined>;
    /**
     * Maximum S3 storage in GB; 0 is unlimited.
     */
    declare public readonly retentionMaxStorageS3: pulumi.Output<number | undefined>;
    /**
     * UUID of the S3 storage (the uuid output of an S3Storage resource). Required when saveS3 is true; the storage must be validated as usable by Coolify.
     */
    declare public readonly s3StorageUuid: pulumi.Output<string | undefined>;
    /**
     * Upload archives to an S3 storage.
     */
    declare public readonly saveS3: pulumi.Output<boolean | undefined>;
    /**
     * UUID of the service owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    declare public readonly serviceUuid: pulumi.Output<string | undefined>;
    /**
     * Stop the containers using the storage while the archive is taken, for consistent snapshots of databases inside services.
     */
    declare public readonly stopDuringBackup: pulumi.Output<boolean | undefined>;
    /**
     * Storage type: persistent or directory.
     */
    declare public /*out*/ readonly storageType: pulumi.Output<string>;
    /**
     * UUID of the storage to back up (the uuid output of a Storage resource or of getStorage). Exactly one of storageUuid and mountPath must be set. Changing it replaces the schedule.
     */
    declare public readonly storageUuid: pulumi.Output<string | undefined>;
    /**
     * Timeout of a backup run in seconds, between 60 and 36000. Leave unset to keep Coolify's default.
     */
    declare public readonly timeout: pulumi.Output<number | undefined>;
    /**
     * UUID of the schedule in Coolify.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * Volume name to disambiguate the mount path when several containers of a service mount the same path. Changing it replaces the schedule.
     */
    declare public readonly volumeName: pulumi.Output<string | undefined>;

    /**
     * Create a VolumeBackup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VolumeBackupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.frequency === undefined && !opts.urn) {
                throw new Error("Missing required property 'frequency'");
            }
            resourceInputs["applicationUuid"] = args?.applicationUuid;
            resourceInputs["backupNow"] = args?.backupNow;
            resourceInputs["databaseUuid"] = args?.databaseUuid;
            resourceInputs["disableLocalBackup"] = args?.disableLocalBackup;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["mountPath"] = args?.mountPath;
            resourceInputs["retentionAmountLocally"] = (args?.retentionAmountLocally) ?? 7;
            resourceInputs["retentionAmountS3"] = (args?.retentionAmountS3) ?? 7;
            resourceInputs["retentionDaysLocally"] = args?.retentionDaysLocally;
            resourceInputs["retentionDaysS3"] = args?.retentionDaysS3;
            resourceInputs["retentionMaxStorageLocally"] = args?.retentionMaxStorageLocally;
            resourceInputs["retentionMaxStorageS3"] = args?.retentionMaxStorageS3;
            resourceInputs["s3StorageUuid"] = args?.s3StorageUuid;
            resourceInputs["saveS3"] = args?.saveS3;
            resourceInputs["serviceUuid"] = args?.serviceUuid;
            resourceInputs["stopDuringBackup"] = args?.stopDuringBackup;
            resourceInputs["storageUuid"] = args?.storageUuid;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["volumeName"] = args?.volumeName;
            resourceInputs["resolvedStorageUuid"] = undefined /*out*/;
            resourceInputs["storageType"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        } else {
            resourceInputs["applicationUuid"] = undefined /*out*/;
            resourceInputs["backupNow"] = undefined /*out*/;
            resourceInputs["databaseUuid"] = undefined /*out*/;
            resourceInputs["disableLocalBackup"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["frequency"] = undefined /*out*/;
            resourceInputs["mountPath"] = undefined /*out*/;
            resourceInputs["resolvedStorageUuid"] = undefined /*out*/;
            resourceInputs["retentionAmountLocally"] = undefined /*out*/;
            resourceInputs["retentionAmountS3"] = undefined /*out*/;
            resourceInputs["retentionDaysLocally"] = undefined /*out*/;
            resourceInputs["retentionDaysS3"] = undefined /*out*/;
            resourceInputs["retentionMaxStorageLocally"] = undefined /*out*/;
            resourceInputs["retentionMaxStorageS3"] = undefined /*out*/;
            resourceInputs["s3StorageUuid"] = undefined /*out*/;
            resourceInputs["saveS3"] = undefined /*out*/;
            resourceInputs["serviceUuid"] = undefined /*out*/;
            resourceInputs["stopDuringBackup"] = undefined /*out*/;
            resourceInputs["storageType"] = undefined /*out*/;
            resourceInputs["storageUuid"] = undefined /*out*/;
            resourceInputs["timeout"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
            resourceInputs["volumeName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VolumeBackup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a VolumeBackup resource.
 */
export interface VolumeBackupArgs {
    /**
     * UUID of the application owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    applicationUuid?: pulumi.Input<string | undefined>;
    /**
     * Run a backup right after creating the schedule. Only relevant on create.
     */
    backupNow?: pulumi.Input<boolean | undefined>;
    /**
     * UUID of the database owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    databaseUuid?: pulumi.Input<string | undefined>;
    /**
     * Keep no local archive once uploaded to S3. Requires saveS3.
     */
    disableLocalBackup?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the schedule is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Cron expression or Coolify shorthand such as "daily" or "0 3 * * *".
     */
    frequency: pulumi.Input<string>;
    /**
     * Mount path of the storage to back up, resolved on the owner. Exactly one of storageUuid and mountPath must be set. Changing it replaces the schedule.
     */
    mountPath?: pulumi.Input<string | undefined>;
    /**
     * Number of archives kept locally; 0 keeps all.
     */
    retentionAmountLocally?: pulumi.Input<number | undefined>;
    /**
     * Number of archives kept in S3; 0 keeps all.
     */
    retentionAmountS3?: pulumi.Input<number | undefined>;
    /**
     * Days local archives are kept; 0 keeps them forever.
     */
    retentionDaysLocally?: pulumi.Input<number | undefined>;
    /**
     * Days S3 archives are kept; 0 keeps them forever.
     */
    retentionDaysS3?: pulumi.Input<number | undefined>;
    /**
     * Maximum local storage in GB; 0 is unlimited.
     */
    retentionMaxStorageLocally?: pulumi.Input<number | undefined>;
    /**
     * Maximum S3 storage in GB; 0 is unlimited.
     */
    retentionMaxStorageS3?: pulumi.Input<number | undefined>;
    /**
     * UUID of the S3 storage (the uuid output of an S3Storage resource). Required when saveS3 is true; the storage must be validated as usable by Coolify.
     */
    s3StorageUuid?: pulumi.Input<string | undefined>;
    /**
     * Upload archives to an S3 storage.
     */
    saveS3?: pulumi.Input<boolean | undefined>;
    /**
     * UUID of the service owning the storage. Exactly one of applicationUuid, databaseUuid and serviceUuid must be set. Changing it replaces the schedule.
     */
    serviceUuid?: pulumi.Input<string | undefined>;
    /**
     * Stop the containers using the storage while the archive is taken, for consistent snapshots of databases inside services.
     */
    stopDuringBackup?: pulumi.Input<boolean | undefined>;
    /**
     * UUID of the storage to back up (the uuid output of a Storage resource or of getStorage). Exactly one of storageUuid and mountPath must be set. Changing it replaces the schedule.
     */
    storageUuid?: pulumi.Input<string | undefined>;
    /**
     * Timeout of a backup run in seconds, between 60 and 36000. Leave unset to keep Coolify's default.
     */
    timeout?: pulumi.Input<number | undefined>;
    /**
     * Volume name to disambiguate the mount path when several containers of a service mount the same path. Changing it replaces the schedule.
     */
    volumeName?: pulumi.Input<string | undefined>;
}
